apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-normal-pv
  namespace: apps
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/app-normal-pv"
  claimRef:
    namespace: apps
    name: app-normal-pvc