apiVersion: v1
kind: Service
metadata:
  name: srv-normal
  namespace: apps
  labels:
    app: normal
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    nodePort: 30000
  selector:
    app: normal
    version: v1