apiVersion: v1
kind: Service
metadata:
  # from "app-secure" pod:
  # curl http://svc-normal.apps:8080
  # curl http://svc-normal:8080
  # curl http://svc-normal.apps.svc.internal:8080
  name: svc-normal
  namespace: apps
  labels:
    app: normal
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    nodePort: 30000
  selector:
    app: normal
    version: v1