apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-showpods
  namespace: apps
  labels:
    app: showpods
spec:
  selector:
    matchLabels:
      app: showpods
  replicas: 1
  
  template:
    metadata:
      labels:
        app: showpods
    spec:
      serviceAccount: showpods-account
      containers:
      - name: showpods
        image: gijsvandulmen/showpods:latest
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          value: "apps"
        resources:
          requests:
            cpu: "10m"
            memory: "101Mi"
          limits:
            cpu: "100m"
            memory: "120Mi"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 600
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
      terminationGracePeriodSeconds: 2