apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: showpods-binding
subjects:
- kind: ServiceAccount
  name: showpods-account
  namespace: apps
roleRef:
  kind: ClusterRole
  name: showpods-role
  apiGroup: rbac.authorization.k8s.io