apiVersion: v1
kind: EphemeralContainers
metadata:
  name: <insert-pod-name>
ephemeralContainers:
- command: ["sh"]
  image: busybox:latest
  imagePullPolicy: IfNotPresent
  name: debugger
  stdin: true
  tty: true
  terminationMessagePolicy: "File"