apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    department: trainees
---
apiVersion: v1
kind: LimitRange
metadata:
  name: apps-limit-ranges
  namespace: apps
spec:
  limits:
  - default:
      memory: "512Mi"
    defaultRequest:
      memory: "256Mi"
    max:
      cpu: "800m"
      memory: "1Gi"
    min:
      cpu: "1m"
      memory: "100Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: apps-resource-quotas
  namespace: apps
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 3Gi
    limits.cpu: "4"
    limits.memory: 3Gi
    pods: "10"