apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-daemonset
  namespace: apps
  labels:
    app: daemonset
spec:
  selector:
    matchLabels:
      app: daemonset
  minReadySeconds: 4
  revisionHistoryLimit: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: daemonset
    spec:
      tolerations:
        # also run on masters!
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: showlogs
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - "tail -f /var/log/containers/app-normal*"
        resources:
          requests:
            cpu: "10m"
            memory: "101Mi"
          limits:
            cpu: "100m"
            memory: "110Mi"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 2
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers