apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-outofmemory
  namespace: apps
  labels:
    app: outofmemory
    version: v1
    team: the-a-team
spec:
  selector:
    matchLabels:
      app: outofmemory
      version: v1
  replicas: 1
  
  # Pod Template Specification
  template:
    metadata:
      labels:
        app: outofmemory
        version: v1
    spec:
      containers:
      - name: outofmemory
        image: gijsvandulmen/outofmemory:latest
        imagePullPolicy: Always
        env:
          - name: ENV_VAR
            value: "value04"
        resources:
          requests:
            cpu: "10m"
            memory: "101Mi"
          limits:
            cpu: "100m"
            memory: "120Mi"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 600
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
      terminationGracePeriodSeconds: 2