apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-statefulset
  namespace: apps
  labels:
    app: statefulset
spec:
  serviceName: statefulset
  selector:
    matchLabels:
      app: statefulset
  replicas: 2

  # normally a statefulset is created in order
  # this allows for pods to be created in parallel
  # using the ordered way one could create a master-slave set
  # where the master is the first pod
  podManagementPolicy: Parallel
  
  # Pod Template Specification
  template:
    metadata:
      labels:
        app: statefulset
    spec:
      containers:
      - name: statefulset
        image: gijsvandulmen/echoserver:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "101Mi"
          limits:
            cpu: "100m"
            memory: "120Mi"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 600
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
      terminationGracePeriodSeconds: 2