apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-donotdisrupt
  namespace: apps
  labels:
    app: donotdisrupt
    version: v1
    team: the-a-team
spec:
  selector:
    matchLabels:
      app: donotdisrupt
      version: v1
  replicas: 2
  
  # Pod Template Specification
  template:
    metadata:
      labels:
        app: donotdisrupt
        version: v1
    spec:
      affinity:
        # make sure the deployment preferes the worker node
        # this will show the disruption budget better
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - k8s-training-m02
      containers:
      - name: donotdisrupt
        image: gijsvandulmen/echoserver:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "101Mi"
          limits:
            cpu: "100m"
            memory: "120Mi"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 600
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
      terminationGracePeriodSeconds: 2